DBT:
  target: dev
  outputs:
    dev:
      type: snowflake
      account: "****" 
      user: "****"
      password: "****"
      role: DATA_ENGINEER_FULL
      database: "CRIME_DB"
      warehouse: "COMPUTE_WH"
      schema: "FINAL"
      threads: 4
      client_session_keep_alive: False
